security:
  jwt:
    secret-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

management:
  tracing:
    sampling:
      probability: 1.0  #Trace everything - 100%
  zipkin:
    tracing:
      endpoint: http://localhost:9411/zipkin/

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"
