security:
  jwt:
    secret-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

management:
  tracing:
    sampling:
      probability: 1.0  #Trace everything - 100%
  zipkin:
    tracing:
      endpoint: http://localhost:9411/zipkin/

logging:
  pattern:
    level: "%5p [${spring.application.name},traceId=%X{traceId},spanId=%X{spanId}]"

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: false
      ignored-networks: 
        - 172.
        - 10.
      ignored-interfaces:
        - vEthernet*
        - WSL*
        - Docker*
